services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/auth_project:/app/backend/auth_project
    ports:
      - "8000:8000"
    networks:
      - auth-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"          # 3000 host, 80 container(nginx)
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
